# Website name
title: Guo Jun | Plasma & Fusion Research

# Website URL（替换为你的 GitHub Pages 链接）
baseURL: "https://kakushun3.github.io/"

# Language Settings
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
removePathAccents: true

languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    title: Guo Jun | Plasma & Fusion Research
    params:
      description: Research in plasma diagnostics and tokamak SOL physics.
    menu:
      main:
        - name: About
          url: '#about'
          weight: 1
        - name: Projects
          url: '#projects'
          weight: 2
        - name: Publications
          url: '#publications'
          weight: 3

  zh:
    languageName: 中文
    weight: 2
    contentDir: content/zh
    title: 郭骏 | 等离子体与聚变研究
    params:
      description: 聚变装置边界层物理与诊断研究
    menu:
      main:
        - name: 关于
          url: '#about'
          weight: 1
        - name: 项目
          url: '#projects'
          weight: 2
        - name: 发表
          url: '#publications'
          weight: 3

  ja:
    languageName: 日本語
    weight: 3
    contentDir: content/ja
    title: 郭駿 | プラズマと核融合研究
    params:
      description: トカマク装置の周辺プラズマ物理と診断技術
    menu:
      main:
        - name: 概要
          url: '#about'
          weight: 1
        - name: プロジェクト
          url: '#projects'
          weight: 2
        - name: 論文
          url: '#publications'
          weight: 3

# Advanced
build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep

