# 设置默认语言为英文
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# 多语言配置
en:
  languageCode: en-us
  contentDir: content/en
  title: Guo Jun | Plasma & Fusion Research
  params:
    description: Research in plasma diagnostics and tokamak SOL physics.
  menu:
    main:
      - name: About
        url: '#about'
        weight: 1
      - name: Projects
        url: '#projects'
        weight: 2
      - name: Publications
        url: '#publications'
        weight: 3

zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 郭骏 | 等离子体与聚变研究
  params:
    description: 聚变装置边界层物理与诊断研究
  menu:
    main:
      - name: 关于
        url: '#about'
        weight: 1
      - name: 项目
        url: '#projects'
        weight: 2
      - name: 发表
        url: '#publications'
        weight: 3

ja:
  languageCode: ja
  contentDir: content/ja
  title: 郭駿 | プラズマと核融合研究
  params:
    description: トカマク装置の周辺プラズマ物理と診断技術
  menu:
    main:
      - name: 概要
        url: '#about'
        weight: 1
      - name: プロジェクト
        url: '#projects'
        weight: 2
      - name: 論文
        url: '#publications'
        weight: 3


